### ISSUE TITLE
quoteColumnName incorrectly handles column names containing AS.

### ISSUE THREAD

**Issue by KuronoKey** [SeinopSys/PHP-PostgreSQL-Database-Class#10]
Method protected function quoteColumnName incorrectly handles column names containing AS (even if it is allowed).
My guess it should return after doing implode:
protected function quoteColumnName($columnName, $allowAs = false)
    {
        $columnName = trim($columnName);
        $hasAs = preg_match('~\S\s+AS\s+\S~i', $columnName);
        if ($allowAs && $hasAs) {
            $columnName = implode(' AS ', $this->quoteColumnNames(preg_split('~\s+AS\s+~i', $columnName)));
            return $columnName; // -- Here is my suggested change
        } 
...

**Comment by SeinopSys** [comment]
Please share the code you believe is causing the library to use incorrect data, it would help greatly.

**Comment by KuronoKey** [comment]
A code like this:
$db->where('c','X');
$foo = $db->getOne('my_table','a as b');

expected query built would be:
SELECT a AS b FROM "my_table" WHERE c='X'
but instead this produced:
SELECT "a AS b" FROM "my_table" WHERE c='X'

That happens because your code in quoteColumnName repeats validation an quoting after implode:
$columnName = implode(' AS ', $this->quoteColumnNames(preg_split('~\s+AS\s+~i', $columnName)));
but that string is already quoted, so (maybe) it'd be good to just return it.

**Comment by SeinopSys** [comment]
Thank you for the detailed report, tests have been updated to make sure this does not break again and I've released `v3.1.0` which contains the fix.
