### ISSUE TITLE
Where to add the DB port?

### ISSUE THREAD

**Issue by daldo** [SeinopSys/PHP-PostgreSQL-Database-Class#12]
Hello,

great job :) Is there a way to add the port number without editing the class?

Thanks a lot :)

**Comment by SeinopSys** [comment]
That's a fair question that I did not think of before. I've just released v3.1.1 which adds a final parameter to the constructor letting you set the port. The [usage guide](https://github.com/SeinopSys/PHP-PostgreSQL-Database-Class/blob/2b0c8ac0c84db86841c94147c70437eceb95ed80/USAGE.md#connecting-to-a-database) has also been updated accordingly. Thank you for your input.
